"""
AgentLens DevUI - Visual Agent Debugging with Orchestrator
===========================================================
Run this to see agent traces in Microsoft Agent Framework DevUI.
Includes an orchestrator workflow that calls all child agents.
"""

import os
from dotenv import load_dotenv

from agent_framework_devui import serve
from agent_framework import HandoffBuilder
from agent_framework.openai import OpenAIChatClient

load_dotenv()

OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")


def create_agents_and_workflow():
    """Create the AgentLens multi-agent team with orchestrator workflow."""
    
    client = OpenAIChatClient(
        api_key=OPENAI_API_KEY,
        model_id="gpt-4o"
    )
    
    # Create the orchestrator/coordinator agent
    orchestrator = client.create_agent(
        name="AgentLens_Orchestrator",
        instructions="""You are the AgentLens Orchestrator that coordinates code analysis.

When a user gives you a codebase or asks for analysis:
1. Hand off to CodeScanner first to scan the codebase
2. Then to BestPracticesChecker for compliance checking  
3. Then to SlopDetector for anti-pattern detection
4. Then to Optimizer for recommendations
5. Finally to ReportCompiler to generate the report

Start by asking the user to paste their code or describe the codebase to analyze.
Then hand off to CodeScanner to begin the analysis pipeline."""
    )
    
    # Agent 1: Code Scanner
    code_scanner = client.create_agent(
        name="CodeScanner",
        instructions="""You are a Code Scanner agent that analyzes AI/ML codebases.
        
EXTRACT:
1. FRAMEWORKS: LangChain, AutoGen, CrewAI, etc.
2. ARCHITECTURE: Single agent, multi-agent, RAG, ReAct
3. LLM_CALLS: ChatOpenAI, Anthropic, invoke(), stream()
4. TOOLS: @tool decorators, Tool classes
5. PATTERNS: Prompt templates, memory, chains

After scanning, hand off to BestPracticesChecker with your findings."""
    )
    
    # Agent 2: Best Practices Checker
    best_practices = client.create_agent(
        name="BestPracticesChecker",
        instructions="""You are a Best Practices Checker agent.
        
Based on the CodeScanner's findings:
1. Score each framework usage 0-100
2. Check against official patterns (LCEL, function calling, prompt caching)
3. Identify compliance gaps

After checking, hand off to SlopDetector with your scores."""
    )
    
    # Agent 3: Slop Detector
    slop_detector = client.create_agent(
        name="SlopDetector",
        instructions="""You are a Slop Detector agent.

Find anti-patterns based on BestPracticesChecker findings:
🔴 CRITICAL: Security issues, exposed keys
🟡 WARNING: Suboptimal patterns, missing error handling
🟢 SUGGESTION: Style improvements

After detecting slop, hand off to Optimizer with your findings."""
    )
    
    # Agent 4: Optimizer
    optimizer = client.create_agent(
        name="Optimizer",
        instructions="""You are an Optimizer agent.
        
Based on SlopDetector findings, suggest:
1. MCP server replacements
2. Cost savings potential
3. Copy-paste code fixes

After optimizing, hand off to ReportCompiler with all recommendations."""
    )
    
    # Agent 5: Report Compiler
    reporter = client.create_agent(
        name="ReportCompiler",
        instructions="""You are the Report Compiler agent.
        
Compile ALL previous agent findings into a professional AgentLens report:
1. Executive Summary (score X/100)
2. Critical Findings with fixes
3. Warnings
4. Strengths
5. Recommendations
6. Action Items

End with: **Report Generated by AgentLens** 🔍

This is the final agent - provide the complete report to the user."""
    )
    
    # Build the orchestration workflow with handoffs
    workflow = (
        HandoffBuilder(
            name="AgentLens_Pipeline",
            participants=[orchestrator, code_scanner, best_practices, slop_detector, optimizer, reporter]
        )
        .set_coordinator(orchestrator)
        .add_handoff(orchestrator, [code_scanner])
        .add_handoff(code_scanner, [best_practices])
        .add_handoff(best_practices, [slop_detector])
        .add_handoff(slop_detector, [optimizer])
        .add_handoff(optimizer, [reporter])
        .enable_return_to_previous(False)
        .build()
    )
    
    # Return both individual agents AND the workflow
    return [
        workflow,  # The orchestrated pipeline (shows as a single entity in DevUI)
        orchestrator,
        code_scanner, 
        best_practices, 
        slop_detector, 
        optimizer, 
        reporter
    ]


if __name__ == "__main__":
    print("\n🔍 AgentLens DevUI with Orchestrator")
    print("=" * 45)
    print("\nStarting DevUI with orchestrated workflow...")
    print("The 'AgentLens_Pipeline' workflow will run all agents in sequence.\n")
    
    entities = create_agents_and_workflow()
    
    # Serve with DevUI
    serve(
        entities=entities,
        tracing_enabled=True,
        port=8080
    )
